# Generated by Django 5.1.4 on 2025-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cart_items_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='cart_prescriptions/'),
        ),
    ]
