# Generated by Django 5.1.4 on 2025-01-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cartitem_prescription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Unknown Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
