# Generated by Django 5.1.5 on 2025-01-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_booking_address_booking_notes_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bookingreport',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('service', 'booking_date', 'appointment_time'), name='unique_booking_slot'),
        ),
    ]
