# Generated by Django 5.1.5 on 2025-01-28 08:02

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_booking_options_alter_bookingreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreport',
            name='report_file',
            field=models.FileField(upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), myapp.models.validate_file_size]),
        ),
    ]
