# Generated by Django 5.1.5 on 2025-01-28 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_bookingreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='booking_reports/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='BookingReport',
        ),
    ]
