# Generated by Django 5.1.5 on 2025-01-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_payment_order_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esewatransaction',
            name='user',
        ),
    ]
