# Generated by Django 5.1.5 on 2025-01-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_esewapayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esewapayment',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='esewapayment',
            name='service_charge',
        ),
    ]
