# Generated by Django 5.1.5 on 2025-02-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_esewapayment_delete_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esewapayment',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='esewapayment',
            name='service_charge',
        ),
        migrations.AddField(
            model_name='esewapayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.order'),
        ),
    ]
